<?php
return [
    [
        'restaurant_id' => 1,
        'name' => 'Marinara',
        'price' => '6',
        'visibility' => true,
        'description' => "Pomodoro S.Marzano, aglio, origano, basilico, olio Evo",
        'image_url' => 'img/restaurant/pizza-marinara.jpg',    /*    img/restaurant/pizza-marinara.jpg    */
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Margherita',
        'price' => '6',
        'visibility' => true,
        'description' => "Pomodoro S.Marzano, Fior di Latte, basilico, olio Evo",
        'image_url' => 'img/restaurant/pizza-margherita.jpg',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Americana',
        'price' => '8',
        'visibility' => true,
        'description' => "Pomodoro S.Marzano, Fior di Latte, Patatine, basilico, olio Evo",
        'image_url' => 'img/restaurant/pizza-patatine.jpg',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Napoli',
        'price' => '8',
        'visibility' => true,
        'description' => "Pomodoro S.Marzano DOP, Fior di Latte, Olive di Gaeta, Acciughe di Sciacca",
        'image_url' => 'img/restaurant/pizza-pachino.jpg',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Bufalina',
        'price' => '8',
        'visibility' => true,
        'description' => "Pomodoro S.Marzano DOP, Bufala Campana DOP, basilico, olio Evo",
        'image_url' => 'img/restaurant/pizza-Bufalina.jpg',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Carbonara',
        'price' => '10',
        'visibility' => true,
        'description' => "Spaghetti,Guanciale, Tuorlo d'Uovo, Pecorino romano DOP",
        'image_url' => 'img/restaurant/carbonara.jpg',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Amatriciana',
        'price' => '10',
        'visibility' => true,
        'description' => "Spaghetti,Guanciale, Pomodoro, Pecorino romano DOP",
        'image_url' => 'img/restaurant/amatriciana.jpg',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Cacio e Pepe',
        'price' => '10',
        'visibility' => true,
        'description' => "Spaghetti,
        Pecorino romano DOP, Pepe",
        'image_url' => 'img/restaurant/caciopepe.jpg',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Salmone al pepe Rosa',
        'price' => '12',
        'visibility' => true,
        'description' => "Trancio di salmone di Alaska, prezzemolo,
        olio Extra Vergine, Pepe Rosa",
        'image_url' => 'img/restaurant/salmone.jpg',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Tartare di Tonno',
        'price' => '13',
        'visibility' => true,
        'description' => "Tartare di Tonno abbattuto, olio Evo, semi di papavero",
        'image_url' => 'img/restaurant/tartare.jpg',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Scaloppine di Pollo al Limone',
        'price' => '13',
        'visibility' => true,
        'description' => "Fettine di pollo marinate al limone, olio, prezzemolo",
        'image_url' => 'img/restaurant/scaloppine.webp',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Petti di Tacchino alla Bolognese',
        'price' => '14',
        'visibility' => true,
        'description' => "Tacchino, Prosciutto crudo, Parmigiano Reggiano DOP, Marsala, Tartufo Nero",
        'image_url' => 'img/restaurant/tacchino.webp',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Patatine Fritte',
        'price' => '4',
        'visibility' => true,
        'description' => "Patatine, Sale",
        'image_url' => 'img/restaurant/patate-fritte.jpg',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Verdure Grigliate',
        'price' => '5',
        'visibility' => true,
        'description' => "Zucchine, Melanzane, Zucca, Peperoni, Olio, Sale, Prezzemolo",
        'image_url' => 'img/restaurant/verdure.jpg',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Patate al Forno',
        'price' => '5',
        'visibility' => true,
        'description' => "Patate, Rosmarino, Olio, Sale",
        'image_url' => 'img/restaurant/forno.webp',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Petti di Tacchino alla Bolognese',
        'price' => '14',
        'visibility' => true,
        'description' => "Tacchino, Prosciutto crudo, Parmigiano Reggiano DOP, Marsala, Tartufo Nero",
        'image_url' => 'img/restaurant/tacchino.webp',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Classico',
        'price' => '6',
        'visibility' => true,
        'description' => "Pane al Sesamo, Hamburger di Fassona 320g, Insalata, Pomodoro, *salse",
        'image_url' => 'img/restaurant/burger.jpg',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'ChickenBurger',
        'price' => '6',
        'visibility' => true,
        'description' => "Pane al Sesamo, Petto di Pollo impanato, Insalata, Pomodoro, *salse",
        'image_url' => 'img/restaurant/burger1.jpg',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'BaconBurger',
        'price' => '6',
        'visibility' => true,
        'description' => "Pane al Sesamo, Hamburger di Maiale, Formaggio, Bacon, *salse",
        'image_url' => 'img/restaurant/burger2.jpg',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Marinara',
        'price' => '6',
        'visibility' => true,
        'description' => "Spaghetti sugo di mare, aglio, origano, basilico, olio Evo",
        'image_url' => 'img/restaurant/spaghetti-mare.jpg',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Samosa',
        'price' => '6',
        'visibility' => true,
        'description' => "Triangolo fritto, ripieno di verdure ",
        'image_url' => 'img/restaurant/samosa.jpg',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Naan',
        'price' => '8',
        'visibility' => true,
        'description' => "Pane cotto nel Tandoor (il tipico forno d’argilla)",
        'image_url' => 'img/restaurant/naan.jpg',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Pollo Tandoori',
        'price' => '8',
        'visibility' => true,
        'description' => "Coscie marinare nello yogurt e altre spezie ",
        'image_url' => 'img/restaurant/pollo-tandori.jpg',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Hamburger di ceci',
        'price' => '8',
        'visibility' => true,
        'description' => "Pane al Sesamo, Hamburger di Ceci, Formaggio, Bacon, *salse",
        'image_url' => 'img/restaurant/hamburger-ceci.jpg',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Focaccia',
        'price' => '5',
        'visibility' => true,
        'description' => "Focaccia, Sale, Olio, ingredienti a scelta",
        'image_url' => 'img/restaurant/pizza-focaccia.jpg',
    ],
    [
        'restaurant_id' => 5,
        'name' => 'Temaki Roll',
        'price' => '5',
        'visibility' => true,
        'description' => "Salmone, Riso, Avocado, Philadelphia, Alga Nori, Maionese",
        'image_url' => 'img/restaurant/temaki.jpg',
    ],
    [
        'restaurant_id' => 5,
        'name' => 'Sashimi',
        'price' => '12',
        'visibility' => true,
        'description' => "Salmone o Tonno fresco abbattuto con Salsa di Soia agli Agrumi",
        'image_url' => 'img/restaurant/sashimi.jpg',
    ],
    [
        'restaurant_id' => 5,
        'name' => 'Uramaki Roll',
        'price' => '8',
        'visibility' => true,
        'description' => "Roll di Riso con Salmone, Tonno o Gamberi, Avocado",
        'image_url' => 'img/restaurant/uramaki.jpg',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Churrasco',
        'price' => '10',
        'visibility' => true,
        'description' => "Carne di Vitello e Maiale alla brace con verdure",
        'image_url' => 'img/restaurant/churrasco.jpg',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Barbecue',
        'price' => '10',
        'visibility' => true,
        'description' => "Grigliata di carne mista",
        'image_url' => 'img/restaurant/grigliata-mista.jpg',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Sacher Torte',
        'price' => '16',
        'visibility' => true,
        'description' => "Torta Sacher farcita con marmellata alle pesche, ricoperta di cioccolato fondente",
        'image_url' => 'img/restaurant/sacher.jpg',
    ],
    [
        'restaurant_id' => 8,
        'name' => 'Spaghetti al pesto di Rucola',
        'price' => '7',
        'visibility' => true,
        'description' => "Spaghetti integrali, pesto di rucola, olio, mandorle",
        'image_url' => 'img/restaurant/spaghetti-pesto.jpg',
    ],
    [
        'restaurant_id' => 8,
        'name' => 'Involtini di Melanzane al forno',
        'price' => '8',
        'visibility' => true,
        'description' => "Involtini di Melanzane con Pomodoro e Zucca",
        'image_url' => 'involtini-melanzane.jpg',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Fritto Misto',
        'price' => '6',
        'visibility' => true,
        'description' => "Fritto misto di mare",
        'image_url' => 'fritto-misto.jpg',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Classico',
        'price' => '6',
        'visibility' => true,
        
        'description' => "Pane al Sesamo, Hamburger di Fassona 320g, Insalata, Pomodoro, *salse",
        'image_url' => 'img/restaurant/burger.jpg',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Pancakes',
        'price' => '6',
        'visibility' => true,
        'description' => "Pancakes americani con frutta e cioccolato",
        'image_url' => 'pancake.jpg',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Torta Mimosa',
        'price' => '10',
        'visibility' => true,
                'description' => "Soffice pan di spagna aromatizzato al limone",
        'image_url' => 'img/restaurant/torta-mimosa.jpg',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Torta al cioccolato',
        'price' => '10',
        'visibility' => true,
                'description' => "Torta a tre diversi tipi di cioccolato",
        'image_url' => 'img/restaurant/torta-cioccolato.jpg',
    ],
];