<?php

return     [
        [
        'name' => 'La Taverna',
        'address' => 'Via Garibaldi, 13',
        'e-mail' => 'taverna@email.it',
        'password' =>'123456',
        'p_iva' => '60028970626',
        'coverImg' => 'la-taverna.jpg',
        ],
        [
        'name' => 'Margherita',
        'address' => 'Via della Posta , 89',
        'e-mail' => 'margherita@email.it',
        'password' =>'123456' ,
        'p_iva' => '60028970626',
        'coverImg' => 'margherita.jpg',
        ],
        [
        'name' => 'Il Chiostro',
        'address' => 'Via del Municipio antico , 6',
        'e-mail' => 'ilchiostro@email.it',
        'password' =>'123456' ,
        'p_iva' => '27178340389',
        'coverImg' => 'il-chiostro.jpg',
        ],
        [
        'name' => 'Due Passi',
        'address' => 'Via della Speranza , 66',
        'e-mail' => 'duepassi@email.it',
        'password' =>'123456' ,
        'p_iva' => '68207150167',
        'coverImg' => 'due-passi.jpg',
        ],
        [
        'name' => 'Itsu',
        'address' => 'Via Alfredo Renzi , 3',
        'e-mail' => 'itsu@email.it',
        'password' =>'123456' ,
        'p_iva' => '47769490088',
        'coverImg' => 'itsu.jpg',
        ],
         [
        'name' => 'The Burger',
        'address' => '	Via della Luna , 4',
        'e-mail' => 'theburger@emial.it',
        'password' =>'123456' ,
        'p_iva' => '47769490088',
        'coverImg' => 'the-burger.jpg',
         ],
         [
        'name' => 'Alla Griglia',
        'address' => 'Via del Domicilio , 3',
        'e-mail' => 'allagriglia@email.it',
        'password' =>'123456' ,
        'p_iva' => '47769490088',
        'coverImg' => 'alla-griglia.jpg',
         ],
        [
        'name' => 'Mi Scusi',
        'address' => 'Via XVII ottobre , 23',
        'e-mail' => 'miscusi@email.it',
        'password' =>'123456' ,
        'p_iva' => '47769490088',
        'coverImg' => 'mi-scusi.jpg',
        ],
        [
        'name' => 'Be Green',
        'address' => 'Via Agostino , 23',
        'e-mail' => 'begreen@email.it',
        'password' =>'123456', 
        'p_iva' => '47769490088',
        'coverImg' => 'be-green.jpg',
        ],
        [
        'name' => 'Zero',
        'address' => 'Via Passatempo , 11',
        'e-mail' => 'zero@email.it',
        'password' =>'123456', 
        'p_iva' => '47769490088',
        'coverImg' => 'zero.jpg',
        ],
    ];